[tool.poetry]
name = "sample-project-for-jeffy"
version = "0.1.0"
description = ""
authors = ["Keisuke Nishitani"]

[tool.poetry.dependencies]
python = "^3.8"
jeffy = "^1.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"