service: jeffy-sample
provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt: [ receiverQueue, Arn ]
plugins:
  - serverless-python-requirements
functions:
  hello:
    handler: handler.hello
  decorator_sample:
    handler: decorator_sample.handler
  sqs-publish:
    handler: sqs_publish.handler
  sqs-subscribe:
    handler: sqs_subscribe.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - receiverQueue
              - Arn
resources:
  Resources:
    receiverQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: jeffy-sample-queue
